### `Conv2DPytTestGroups` code

In [281]:
import numpy as np

In [282]:
class Conv2DPytTestGroups:
    ''' Computes convolution given the input parameters '''
    
    ''' * The class implementation will be along the lines of torch.nn.Conv2D in order to 
          enable comparison of this NumPy only implementation and seamless testing
        * Can expect extensive refactoring of the existing code in the days to come
        * As part of refactoring, some code will be de-modularized
        * Old code will be retained at the end of the notebook for reference
    '''
    '''
        TODO:
        * Fix `groups` implementation to make it more robust - some tests failing
        * Implementing other features and caveats offered by nn.torch.Conv2D 
          (e.g., uniform sampling of kernel weights etc.)
        * Optimizing code
    '''
    
    def __init__(
        self, 
        in_channels, 
        out_channels, 
        kernel_size, 
        padding = 0, 
        stride = 1, 
        dilation = 1, 
        groups = 1, 
        bias = True, 
        padding_mode = 'zeros', 
        device = None, 
        dtype = None, 
        verbose = True, 
        debug = False
        ):
        super(Conv2DPytTestGroups, self).__init__()
        
        ''' mandatory parameters '''
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        
        ''' optional parameters '''
        self.padding = padding
        self.stride = stride
        self.dilation = dilation
        self.groups = groups
        
        ''' optional parameters (dummy, yet to be implemented)'''
        self.bias = bias
        self.padding_mode = padding_mode
        self.device = device
        self.dtype = dtype
        
        ''' additional parameters (different from torch.nn.Conv2D)'''
        self.verbose = verbose
        self.verboseprint = print if self.verbose else lambda *a, **k: None
        self.debug = debug
        self.debugprint = print if self.debug else lambda *a, **k: None
        self.verboseprint('*** parameters ***')
        self.verboseprint('in_channels: {}, out_channels: {}, kernel_size: {}'.format(self.in_channels, self.out_channels, self.kernel_size))
        self.verboseprint('padding: {}, stride: {}, dilation factor: {}'.format(self.padding, self.stride, self.dilation))
        self.verboseprint('groups: {}, bias: {}, padding_mode: {}, device: {}, dtype: {}'.format(self.groups, self.bias, self.padding_mode, self.device, self.dtype))
        self.verboseprint('\n')
    
    def forward(self, _input, kernels):
        ''' forward pass to perform convolution '''
        
        ''' do error checking '''
        _input_n, _input_c, _input_h, _input_w = _input.shape
        if _input_h + 2 * self.padding < self.dilation * (self.kernel_size[0] - 1) + 1: # check if (dilated) ker_h is valid
            raise Exception('invalid input parameters: kernel height is larger than input height')
        if _input_w + 2 * self.padding < self.dilation * (self.kernel_size[1] - 1) + 1: # check if (dilated) ker_w is valid
            raise Exception('invalid input parameters: kernel width is larger than input width')
        if ((_input_h + 2 * self.padding - (self.dilation * (self.kernel_size[0] - 1) + 1)) / self.stride) + 1 < 0: # check if out_h is valid
            raise Exception('invalid input parameters: output height is negative')
        if ((_input_h + 2 * self.padding - (self.dilation * (self.kernel_size[1] - 1) + 1)) / self.stride) + 1 < 0: # check if out_w is valid
            raise Exception('invalid input parameters: output width is negative')
        if  self.in_channels % self.groups != 0: # check if groups is valid
            raise Exception('invalid input parameters: input channels is not divisible by groups')
        if self.out_channels % self.groups != 0: # check if groups is valid
            raise Exception('invalid input parametes: output channels is not divisible by groups')
         
        ''' add zero padding based on the input parameters '''
        if self.padding != 0:
            _input = np.array([[np.pad(channel,self.padding, 'constant', constant_values = 0) for channel in batch] for batch in _input])    
            self.verboseprint('*** padded input image ***')
            self.verboseprint('input batches: {}, input channels: {}, input height: {}, input weight: {}'.format(_input.shape[0], _input.shape[1], _input.shape[2], _input.shape[3]))
            self.verboseprint(_input)
            self.verboseprint('\n')
        if self.debug:
            for b in range(_input.shape[0]):
                _input[b] = (b+1) * np.ones_like(_input[b]) # define an image of all ones (twos etc.) based on the input parameters
        
        ''' use the provided kernels or create random kernels based on the input kernel parameters '''
        if kernels is not None:
            self.verboseprint('*** kernels ***')
            self.verboseprint('kernels: {}, kernel channels: {}, kernel height: {}, kernel weight: {}'.format(self.out_channels, int(self.in_channels / self.groups), self.kernel_size[0], self.kernel_size[1]))
        else:
            kernels = []
            self.verboseprint('*** kernels ***')
            self.verboseprint('kernels: {}, kernel channels: {}, kernel height: {}, kernel weight: {}'.format(self.out_channels, int(self.in_channels / self.groups), self.kernel_size[0], self.kernel_size[1]))
            for k in range(self.out_channels):
                kernel = np.random.rand(int(self.in_channels/self.groups), self.kernel_size[0], self.kernel_size[1]) # define a random kernel based on the kernel parameters
                if self.debug:
                    kernel = k * np.ones_like(kernel)
                kernels.append(kernel)
                self.verboseprint('kernel {}'.format(k))
                self.verboseprint(kernel)
            self.verboseprint('\n')
        
        ''' dilate a kernel '''
        dil_ker_h = self.dilation * (self.kernel_size[0] - 1) + 1
        dil_ker_w = self.dilation * (self.kernel_size[1] - 1) + 1
        dil_kernels = []
        for kernel in kernels:
            dil_kernel = []
            for channel in kernel:
                dil_channel = np.zeros((dil_ker_h, dil_ker_w))
                for row in range(len(channel)):
                    for col in range(len(channel[0])):
                        dil_channel[self.dilation*row][self.dilation*col] = channel[row][col]
                dil_kernel.append(dil_channel.tolist())
            dil_kernels.append(dil_kernel)
        kernels, self.kernel_size = dil_kernels, (dil_ker_h, dil_ker_w)
        self.verboseprint('*** dilated kernels ***')
        self.verboseprint('kernels: {}, dilation factor: {}, kernel channels: {}, kernel height: {}, kernel weight: {}'.format(self.out_channels, self.dilation, int(self.in_channels / self.groups), self.kernel_size[0], self.kernel_size[1]))
        for k in range(self.out_channels):
            self.verboseprint('kernel {}'.format(k))
            self.verboseprint(kernels[k])
        self.verboseprint('\n')
        
        ''' compute output volume from the input and kernel parameters '''
        _input_n, _, _input_h, _input_w = _input.shape
        out_n = int(_input_n)
        out_c = int(self.out_channels)
        out_h = int((_input_h - self.kernel_size[0])/self.stride) + 1
        out_w = int((_input_w - self.kernel_size[1])/self.stride) + 1
        output = np.zeros([out_n, out_c, out_h, out_w])
        
        ''' parse through every element of the output and compute the convolution value for that element '''
        for b in range(out_n):
            for k in range(out_c):
                for h in range(out_h):
                    for w in range(out_w):
                        # convolve kernel over the input slices
                        self.debugprint('kernel indices, image indices')
                        self.debugprint('[c, h, w]', '[n, c, h, w]')
                        convol_sum = 0
                        ker_c = int(self.in_channels / self.groups)
                        ker_h = self.kernel_size[0]
                        ker_w = self.kernel_size[1]
                        for c_ker in range(ker_c):
                            for h_ker in range(ker_h):
                                for w_ker in range(ker_w):
                                    if self.groups == 1:
                                        self.debugprint([k, c_ker, h_ker, w_ker], [b, c_ker, h_ker + self.stride * h, w_ker + self.stride * w])
                                        convol_sum += kernels[k][c_ker][h_ker][w_ker] * _input[b][c_ker][h_ker + self.stride*h][w_ker + self.stride*w] # if groups == 1
                                    elif self.groups == self.in_channels:
                                        self.debugprint([k, c_ker, h_ker, w_ker], [b, k, h_ker + self.stride * h, w_ker + self.stride * w])
                                        convol_sum += kernels[k][c_ker][h_ker][w_ker] * _input[b][k][h_ker + self.stride * h][w_ker + self.stride * w] # if groups == in_channels
                                    else:
                                        self.debugprint([k, c_ker, h_ker, w_ker], [b, c_ker if k < self.groups else c_ker + ker_c, h_ker + self.stride * h, w_ker + self.stride * w])
                                        convol_sum += kernels[k][c_ker][h_ker][w_ker] * _input[b][c_ker if k < self.groups else c_ker + ker_c][h_ker + self.stride * h][w_ker + self.stride * w] # if 1 < groups < in_channels
                        self.debugprint('\n')
                        output[b, k, h, w] += convol_sum
        self.verboseprint('*** Conv2DPytTest output ***')
        output_shape = output.shape
        self.verboseprint('output batches: {}, ouput channels: {}, output height: {}, output weight: {}'.format(output_shape[0], output_shape[1], output_shape[2], output_shape[3]))
        assert((out_n, out_c, out_h, out_w) == output_shape)
        self.verboseprint(output)
        self.verboseprint('\n')
        return output

### Standalone test (random kernel, random input)

In [283]:
debug = False # DO NOT CHANGE THIS while using Conv2DPytTestGroups - TODO: modify this flag to `test`

in_channels = 6 # input channels
out_channels = 4 # output channels
kernel_size = (2, 2) # kernel size

padding = 1 # padding (optional)
stride = 2 # stride (optional)
dilation = 1 # dilation factor (optional)
groups = 2 # groups (optional)

in_batches = 2 # input batches
in_h = 4 # input height
in_w = 4 # input weight

_input = np.random.rand(in_batches, in_channels, in_h, in_w) # define a random image based on the input parameters
kernels = []
for k in range(out_channels):
    kernel = np.random.rand(int(in_channels / groups), kernel_size[0], kernel_size[1]) # define a random kernel based on the kernel parameters
    kernels.append(kernel)

In [284]:
# get Conv2DPytTestGroups output with the random inputs

conv2dpyttestgroups = Conv2DPytTestGroups(in_channels, out_channels, kernel_size, stride = stride, padding = padding, dilation = dilation, groups = groups, debug = debug, verbose = False) # call an instance of the class with the input parameters 
_output = conv2dpyttestgroups.forward(_input, kernels) # perform convolution
print("*** Conv2DPytTestGroups output ***")
print(_output)

*** Conv2DPytTestGroups output ***
[[[[0.70427929 2.82019084 0.40261863]
   [1.54349942 3.35092143 1.13886681]
   [0.15326395 1.31998229 0.81070694]]

  [[0.54893892 2.10956146 0.52147893]
   [2.04195267 3.94973766 1.2034504 ]
   [0.55683908 1.47607389 0.69651989]]

  [[0.62516699 1.18566361 0.4936451 ]
   [2.59164193 3.02877504 0.71158585]
   [0.76244125 1.96040352 0.3562567 ]]

  [[0.6692644  1.53056299 1.11834824]
   [1.32763088 2.89185683 1.74017708]
   [0.48735152 1.84209336 1.11125937]]]


 [[[0.6128883  1.14325889 0.70231473]
   [2.3061121  2.80073564 0.67622515]
   [0.48600849 1.42516353 1.03900796]]

  [[0.58537121 0.96336564 0.70591761]
   [1.7755101  2.7285069  0.59874787]
   [0.836532   2.13708475 0.83282811]]

  [[0.58247132 1.52525674 0.24810848]
   [1.56954752 2.13698187 0.86372561]
   [1.16611727 1.18447742 0.20073716]]

  [[0.67099181 1.32553127 0.49698438]
   [1.23806643 2.68759124 1.63231083]
   [0.37516915 1.49920869 0.6274384 ]]]]


In [285]:
# get PyTorch output with the same random inputs as above

import torch

x = torch.DoubleTensor(_input)
weights = torch.stack([torch.DoubleTensor(kernel) for kernel in kernels])
output = torch.nn.functional.conv2d(x, weights, stride = stride, padding = padding, groups = groups)
print("*** PyTorch output ***")
print(output)

*** PyTorch output ***
tensor([[[[0.7043, 2.8202, 0.4026],
          [1.5435, 3.3509, 1.1389],
          [0.1533, 1.3200, 0.8107]],

         [[0.5489, 2.1096, 0.5215],
          [2.0420, 3.9497, 1.2035],
          [0.5568, 1.4761, 0.6965]],

         [[0.6252, 1.1857, 0.4936],
          [2.5916, 3.0288, 0.7116],
          [0.7624, 1.9604, 0.3563]],

         [[0.6693, 1.5306, 1.1183],
          [1.3276, 2.8919, 1.7402],
          [0.4874, 1.8421, 1.1113]]],


        [[[0.6129, 1.1433, 0.7023],
          [2.3061, 2.8007, 0.6762],
          [0.4860, 1.4252, 1.0390]],

         [[0.5854, 0.9634, 0.7059],
          [1.7755, 2.7285, 0.5987],
          [0.8365, 2.1371, 0.8328]],

         [[0.5825, 1.5253, 0.2481],
          [1.5695, 2.1370, 0.8637],
          [1.1661, 1.1845, 0.2007]],

         [[0.6710, 1.3255, 0.4970],
          [1.2381, 2.6876, 1.6323],
          [0.3752, 1.4992, 0.6274]]]], dtype=torch.float64)


In [286]:
# compare outputs of conv-Numpy and PyTorch
print(torch.equal(torch.round(torch.DoubleTensor(_output)), torch.round(output))) # need to round the output due to precision difference

True


### Extensive tests (random kernel, random input)

In [289]:
def valid_params(num_tests):
    # generates `num_samples` number of valid input and kernel parameters 
    params_list = []
    sample_count = 0
    while sample_count < num_tests:
        in_channels = np.random.randint(20) + 1 # input channels
        out_channels = np.random.randint(in_channels) + 1 # output channels
        
        ker_h = np.random.randint(20) + 1
        ker_w = np.random.randint(20) + 1
        kernel_size = (ker_h, ker_w) # kernel size
        
        padding = np.random.randint(10) + 1 # padding (optional)
        stride = np.random.randint(5) + 1 # stride (optional)
        dilation = np.random.randint(10) + 1 # dilation factor (optional)
        groups = np.random.randint(in_channels) + 1 # groups (optional)
        
        in_batches = np.random.randint(5) + 1 # input batches
        in_h = np.random.randint(30) + 5 # input height
        in_w = np.random.randint(30) + 5 # input weight
    
        ker_h_flag, ker_w_flag, out_h_flag, out_w_flag, in_group_flag, out_group_flag = True, True, True, True, True, True
        
        if in_h + 2 * padding < dilation * (ker_h - 1) + 1: # check if (dilated) ker_h is valid
            ker_h_flag = False
        if in_w + 2 * padding < dilation * (ker_w - 1) + 1: # check if (dilated) ker_w is valid
            ker_w_flag = False
        if ((in_h + 2 * padding - (dilation * (ker_h - 1) + 1)) / stride) + 1 < 0: # check if out_h is valid
            out_h_flag = False
        if ((in_w + 2 * padding - (dilation * (ker_w - 1) + 1)) / stride) + 1 < 0: # check if out_w is valid
            out_w_flag = False
        if  in_channels % groups != 0: # check if groups is valid
            in_group_flag = False
        if out_channels % groups != 0: # check if groups is valid
            out_group_flag = False
        
        if ker_h_flag and ker_w_flag and out_h_flag and out_w_flag and in_group_flag and out_group_flag:
            params_list.append({'in_channels': in_channels, 'out_channels': out_channels, 'kernel_size': kernel_size,
                          'padding': padding, 'stride': stride, 'dilation': dilation, 'groups': groups, 'in_batches': in_batches,
                          'in_h': in_h, 'in_w': in_w})
            sample_count += 1
    return params_list

In [290]:
# for loop sweeping different input parameters and testing the outputs of Conv2DPytTestGroups and PyTorch
from tqdm import tqdm

num_tests = 100 # only test parameter to be varied
num_passed = 0
params_list = valid_params(num_tests)
print('Number of tests: {}\n\n'.format(len(params_list)))

for i, params in enumerate(tqdm(params_list)):
    print('Test: {}\nParams: {}'.format(i, params))
    debug = False # DO NOT CHANGE THIS while using Conv2DPytTest - TODO: modify this flag to `test`

    in_channels = params['in_channels'] # input channels
    out_channels = params['out_channels'] # output channels
    
    kernel_size = params['kernel_size'] # kernel size

    padding = params['padding'] # padding (optional)
    stride = params['stride'] # stride (optional)
    dilation = params['dilation'] # dilation factor (optional)
    groups = params['groups'] # groups (optional)
    
    in_batches = params['in_batches'] # input batches
    in_h = params['in_h'] # input height
    in_w = params['in_w'] # input weight
    
    _input = np.random.rand(in_batches, in_channels, in_h, in_w) # define a random image based on the input parameters
    kernels = []
    for k in range(out_channels):
        kernel = np.random.rand(int(in_channels / groups), kernel_size[0], kernel_size[1]) # define a random kernel based on the kernel parameters
        kernels.append(kernel)
    
    try:
        # get Conv2DPytTest output with the random inputs
        conv2dpyttestgroups = Conv2DPytTestGroups(in_channels, out_channels, kernel_size, stride = stride, padding = padding, dilation = dilation, groups = groups, debug = debug, verbose = False) # call an instance of the class with the input parameters 
        _output = conv2dpyttestgroups.forward(_input, kernels) # perform convolution

        # get PyTorch output with the same random inputs as above
        x = torch.DoubleTensor(_input)
        weights = torch.stack([torch.DoubleTensor(kernel) for kernel in kernels])
        output = torch.nn.functional.conv2d(x, weights, stride = stride, padding = padding, dilation = dilation, groups = groups)
        
    except Exception as e:
        print(e)
        pass
    
    # compare outputs of conv-Numpy and PyTorch
    result = torch.equal(torch.round(torch.DoubleTensor(_output)), torch.round(output)) # need to round the output due to precision difference
    print('Result: {}\n\n'.format(result))
    if result:
        num_passed += 1

print('{} out of {} ({}%) tests passed'.format(num_passed, num_tests, float(100 * num_passed / num_tests)))
    

Number of tests: 100




  0%|                                                   | 0/100 [00:00<?, ?it/s]

Test: 0
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (5, 10), 'padding': 3, 'stride': 1, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 7, 'in_w': 20}
invalid input parameters: output width is negative
Result: True


Test: 1
Params: {'in_channels': 3, 'out_channels': 3, 'kernel_size': (10, 18), 'padding': 3, 'stride': 2, 'dilation': 1, 'groups': 3, 'in_batches': 5, 'in_h': 15, 'in_w': 12}
Result: True


Test: 2
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (2, 1), 'padding': 1, 'stride': 1, 'dilation': 5, 'groups': 1, 'in_batches': 3, 'in_h': 16, 'in_w': 20}
Result: True


Test: 3
Params: {'in_channels': 13, 'out_channels': 13, 'kernel_size': (4, 6), 'padding': 6, 'stride': 5, 'dilation': 3, 'groups': 13, 'in_batches': 5, 'in_h': 19, 'in_w': 20}


  4%|█▋                                         | 4/100 [00:00<00:13,  6.94it/s]

Result: True


Test: 4
Params: {'in_channels': 3, 'out_channels': 1, 'kernel_size': (3, 11), 'padding': 10, 'stride': 3, 'dilation': 3, 'groups': 1, 'in_batches': 3, 'in_h': 34, 'in_w': 21}


  6%|██▌                                        | 6/100 [00:01<00:16,  5.58it/s]

Result: True


Test: 5
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (1, 6), 'padding': 10, 'stride': 1, 'dilation': 3, 'groups': 1, 'in_batches': 5, 'in_h': 31, 'in_w': 10}
Result: True


Test: 6
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (5, 2), 'padding': 4, 'stride': 4, 'dilation': 3, 'groups': 1, 'in_batches': 4, 'in_h': 18, 'in_w': 32}


  7%|███                                        | 7/100 [00:01<00:16,  5.59it/s]

Result: True


Test: 7
Params: {'in_channels': 11, 'out_channels': 3, 'kernel_size': (10, 5), 'padding': 2, 'stride': 2, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 15, 'in_w': 24}


  8%|███▍                                       | 8/100 [00:01<00:27,  3.34it/s]

Result: True


Test: 8
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (8, 13), 'padding': 9, 'stride': 1, 'dilation': 2, 'groups': 1, 'in_batches': 5, 'in_h': 12, 'in_w': 26}


  9%|███▊                                       | 9/100 [00:03<01:03,  1.44it/s]

Result: True


Test: 9
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (9, 10), 'padding': 7, 'stride': 2, 'dilation': 2, 'groups': 2, 'in_batches': 4, 'in_h': 25, 'in_w': 24}


 10%|████▏                                     | 10/100 [00:04<01:19,  1.13it/s]

Result: True


Test: 10
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (4, 13), 'padding': 8, 'stride': 4, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 6, 'in_w': 20}
Result: True


Test: 11
Params: {'in_channels': 6, 'out_channels': 2, 'kernel_size': (16, 12), 'padding': 3, 'stride': 4, 'dilation': 1, 'groups': 1, 'in_batches': 3, 'in_h': 19, 'in_w': 33}


 13%|█████▍                                    | 13/100 [00:05<00:42,  2.05it/s]

Result: True


Test: 12
Params: {'in_channels': 6, 'out_channels': 3, 'kernel_size': (7, 3), 'padding': 6, 'stride': 5, 'dilation': 2, 'groups': 1, 'in_batches': 3, 'in_h': 6, 'in_w': 31}
Result: True


Test: 13
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (3, 4), 'padding': 3, 'stride': 4, 'dilation': 9, 'groups': 1, 'in_batches': 3, 'in_h': 16, 'in_w': 33}
invalid input parameters: output width is negative
Result: True


Test: 14
Params: {'in_channels': 9, 'out_channels': 3, 'kernel_size': (6, 9), 'padding': 2, 'stride': 3, 'dilation': 1, 'groups': 3, 'in_batches': 2, 'in_h': 18, 'in_w': 6}
Result: False


Test: 15
Params: {'in_channels': 16, 'out_channels': 1, 'kernel_size': (3, 1), 'padding': 8, 'stride': 3, 'dilation': 6, 'groups': 1, 'in_batches': 5, 'in_h': 6, 'in_w': 11}


 16%|██████▋                                   | 16/100 [00:05<00:22,  3.78it/s]

Result: True


Test: 16
Params: {'in_channels': 3, 'out_channels': 3, 'kernel_size': (12, 12), 'padding': 10, 'stride': 3, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 32, 'in_w': 21}


 17%|███████▏                                  | 17/100 [00:10<01:32,  1.11s/it]

Result: True


Test: 17
Params: {'in_channels': 3, 'out_channels': 3, 'kernel_size': (18, 1), 'padding': 9, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 14, 'in_w': 9}
Result: True


Test: 18
Params: {'in_channels': 11, 'out_channels': 5, 'kernel_size': (19, 17), 'padding': 10, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 31, 'in_w': 27}


 19%|███████▉                                  | 19/100 [00:15<02:16,  1.68s/it]

Result: True


Test: 19
Params: {'in_channels': 4, 'out_channels': 2, 'kernel_size': (15, 8), 'padding': 7, 'stride': 2, 'dilation': 2, 'groups': 2, 'in_batches': 3, 'in_h': 16, 'in_w': 32}


 20%|████████▍                                 | 20/100 [00:15<01:50,  1.38s/it]

Result: False


Test: 20
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (17, 9), 'padding': 7, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 18, 'in_w': 22}
Result: True


Test: 21
Params: {'in_channels': 3, 'out_channels': 1, 'kernel_size': (5, 2), 'padding': 4, 'stride': 5, 'dilation': 9, 'groups': 1, 'in_batches': 1, 'in_h': 32, 'in_w': 6}
Result: True


Test: 22
Params: {'in_channels': 5, 'out_channels': 3, 'kernel_size': (13, 5), 'padding': 6, 'stride': 1, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 17, 'in_w': 25}


 23%|█████████▋                                | 23/100 [00:20<01:56,  1.51s/it]

Result: True


Test: 23
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (3, 18), 'padding': 10, 'stride': 4, 'dilation': 1, 'groups': 2, 'in_batches': 4, 'in_h': 9, 'in_w': 22}
Result: True


Test: 24
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (11, 9), 'padding': 8, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 5, 'in_h': 29, 'in_w': 8}


 25%|██████████▌                               | 25/100 [00:21<01:21,  1.08s/it]

Result: True


Test: 25
Params: {'in_channels': 2, 'out_channels': 1, 'kernel_size': (10, 3), 'padding': 5, 'stride': 5, 'dilation': 2, 'groups': 1, 'in_batches': 2, 'in_h': 23, 'in_w': 25}
Result: True


Test: 26
Params: {'in_channels': 2, 'out_channels': 1, 'kernel_size': (12, 18), 'padding': 8, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 5, 'in_h': 34, 'in_w': 7}


 27%|███████████▎                              | 27/100 [00:21<00:57,  1.28it/s]

Result: True


Test: 27
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (11, 12), 'padding': 10, 'stride': 2, 'dilation': 4, 'groups': 1, 'in_batches': 2, 'in_h': 30, 'in_w': 25}


 28%|███████████▊                              | 28/100 [00:21<00:49,  1.46it/s]

Result: True


Test: 28
Params: {'in_channels': 15, 'out_channels': 7, 'kernel_size': (20, 14), 'padding': 8, 'stride': 4, 'dilation': 1, 'groups': 1, 'in_batches': 2, 'in_h': 23, 'in_w': 17}


 29%|████████████▏                             | 29/100 [00:25<01:40,  1.41s/it]

Result: True


Test: 29
Params: {'in_channels': 3, 'out_channels': 2, 'kernel_size': (2, 2), 'padding': 2, 'stride': 3, 'dilation': 8, 'groups': 1, 'in_batches': 5, 'in_h': 34, 'in_w': 26}


 30%|████████████▌                             | 30/100 [00:26<01:23,  1.20s/it]

Result: True


Test: 30
Params: {'in_channels': 4, 'out_channels': 2, 'kernel_size': (9, 16), 'padding': 8, 'stride': 3, 'dilation': 2, 'groups': 1, 'in_batches': 3, 'in_h': 26, 'in_w': 16}


 31%|█████████████                             | 31/100 [00:26<01:06,  1.03it/s]

Result: True


Test: 31
Params: {'in_channels': 6, 'out_channels': 4, 'kernel_size': (6, 8), 'padding': 6, 'stride': 1, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 19, 'in_w': 27}


 32%|█████████████▍                            | 32/100 [00:30<01:51,  1.64s/it]

Result: True


Test: 32
Params: {'in_channels': 3, 'out_channels': 2, 'kernel_size': (11, 9), 'padding': 4, 'stride': 5, 'dilation': 1, 'groups': 1, 'in_batches': 3, 'in_h': 18, 'in_w': 18}
Result: True


Test: 33
Params: {'in_channels': 5, 'out_channels': 4, 'kernel_size': (15, 3), 'padding': 9, 'stride': 5, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 6, 'in_w': 19}


 34%|██████████████▎                           | 34/100 [00:30<01:05,  1.01it/s]

Result: True


Test: 34
Params: {'in_channels': 8, 'out_channels': 7, 'kernel_size': (13, 4), 'padding': 9, 'stride': 5, 'dilation': 2, 'groups': 1, 'in_batches': 5, 'in_h': 24, 'in_w': 23}


 35%|██████████████▋                           | 35/100 [00:34<01:53,  1.74s/it]

Result: True


Test: 35
Params: {'in_channels': 3, 'out_channels': 3, 'kernel_size': (5, 4), 'padding': 7, 'stride': 4, 'dilation': 6, 'groups': 3, 'in_batches': 2, 'in_h': 18, 'in_w': 16}
Result: True


Test: 36
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (16, 3), 'padding': 9, 'stride': 1, 'dilation': 2, 'groups': 1, 'in_batches': 5, 'in_h': 31, 'in_w': 30}


 39%|████████████████▍                         | 39/100 [00:36<00:56,  1.07it/s]

Result: True


Test: 37
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (11, 10), 'padding': 8, 'stride': 5, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 12, 'in_w': 14}
Result: True


Test: 38
Params: {'in_channels': 6, 'out_channels': 6, 'kernel_size': (2, 12), 'padding': 4, 'stride': 2, 'dilation': 1, 'groups': 2, 'in_batches': 1, 'in_h': 10, 'in_w': 20}
Result: False


Test: 39
Params: {'in_channels': 4, 'out_channels': 2, 'kernel_size': (9, 11), 'padding': 9, 'stride': 4, 'dilation': 1, 'groups': 2, 'in_batches': 4, 'in_h': 32, 'in_w': 27}


 40%|████████████████▊                         | 40/100 [00:36<00:49,  1.21it/s]

Result: False


Test: 40
Params: {'in_channels': 5, 'out_channels': 3, 'kernel_size': (1, 11), 'padding': 9, 'stride': 1, 'dilation': 4, 'groups': 1, 'in_batches': 3, 'in_h': 25, 'in_w': 34}


 41%|█████████████████▏                        | 41/100 [00:40<01:20,  1.36s/it]

Result: True


Test: 41
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (1, 6), 'padding': 5, 'stride': 5, 'dilation': 1, 'groups': 1, 'in_batches': 2, 'in_h': 11, 'in_w': 27}
Result: True


Test: 42
Params: {'in_channels': 14, 'out_channels': 4, 'kernel_size': (14, 9), 'padding': 8, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 27, 'in_w': 12}


 44%|██████████████████▍                       | 44/100 [00:43<01:05,  1.17s/it]

Result: True


Test: 43
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (9, 3), 'padding': 5, 'stride': 1, 'dilation': 3, 'groups': 1, 'in_batches': 2, 'in_h': 16, 'in_w': 27}
Result: True


Test: 44
Params: {'in_channels': 7, 'out_channels': 6, 'kernel_size': (12, 4), 'padding': 8, 'stride': 4, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 8, 'in_w': 8}


 45%|██████████████████▉                       | 45/100 [00:43<00:55,  1.02s/it]

Result: True


Test: 45
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (10, 9), 'padding': 7, 'stride': 1, 'dilation': 4, 'groups': 1, 'in_batches': 2, 'in_h': 24, 'in_w': 32}


 46%|███████████████████▎                      | 46/100 [00:45<00:56,  1.05s/it]

Result: True


Test: 46
Params: {'in_channels': 9, 'out_channels': 2, 'kernel_size': (13, 1), 'padding': 9, 'stride': 2, 'dilation': 3, 'groups': 1, 'in_batches': 5, 'in_h': 22, 'in_w': 18}


 47%|███████████████████▋                      | 47/100 [00:45<00:45,  1.16it/s]

Result: True


Test: 47
Params: {'in_channels': 18, 'out_channels': 17, 'kernel_size': (10, 1), 'padding': 9, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 6, 'in_w': 13}


 48%|████████████████████▏                     | 48/100 [00:45<00:39,  1.32it/s]

Result: True


Test: 48
Params: {'in_channels': 4, 'out_channels': 1, 'kernel_size': (12, 9), 'padding': 7, 'stride': 3, 'dilation': 2, 'groups': 1, 'in_batches': 2, 'in_h': 15, 'in_w': 28}


 50%|█████████████████████                     | 50/100 [00:46<00:23,  2.17it/s]

Result: True


Test: 49
Params: {'in_channels': 6, 'out_channels': 4, 'kernel_size': (10, 12), 'padding': 5, 'stride': 5, 'dilation': 1, 'groups': 2, 'in_batches': 1, 'in_h': 25, 'in_w': 24}
Result: True


Test: 50
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (3, 17), 'padding': 4, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 6, 'in_w': 34}
invalid input parameters: output width is negative
Result: True


Test: 51
Params: {'in_channels': 4, 'out_channels': 4, 'kernel_size': (14, 20), 'padding': 8, 'stride': 5, 'dilation': 1, 'groups': 2, 'in_batches': 5, 'in_h': 30, 'in_w': 13}


 52%|█████████████████████▊                    | 52/100 [00:46<00:16,  2.90it/s]

Result: True


Test: 52
Params: {'in_channels': 4, 'out_channels': 3, 'kernel_size': (8, 4), 'padding': 8, 'stride': 2, 'dilation': 5, 'groups': 1, 'in_batches': 3, 'in_h': 20, 'in_w': 18}


 53%|██████████████████████▎                   | 53/100 [00:47<00:17,  2.64it/s]

Result: True


Test: 53
Params: {'in_channels': 9, 'out_channels': 3, 'kernel_size': (4, 1), 'padding': 10, 'stride': 3, 'dilation': 7, 'groups': 1, 'in_batches': 2, 'in_h': 28, 'in_w': 14}


 54%|██████████████████████▋                   | 54/100 [00:47<00:17,  2.67it/s]

Result: True


Test: 54
Params: {'in_channels': 6, 'out_channels': 2, 'kernel_size': (15, 9), 'padding': 6, 'stride': 2, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 29, 'in_w': 5}


 55%|███████████████████████                   | 55/100 [00:47<00:17,  2.60it/s]

Result: True


Test: 55
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (4, 7), 'padding': 6, 'stride': 4, 'dilation': 7, 'groups': 1, 'in_batches': 5, 'in_h': 21, 'in_w': 32}
invalid input parameters: output width is negative
Result: True


Test: 56
Params: {'in_channels': 4, 'out_channels': 3, 'kernel_size': (1, 13), 'padding': 3, 'stride': 5, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 11, 'in_w': 32}
invalid input parameters: output width is negative
Result: True


Test: 57
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (4, 2), 'padding': 4, 'stride': 3, 'dilation': 2, 'groups': 1, 'in_batches': 1, 'in_h': 34, 'in_w': 27}
Result: True


Test: 58
Params: {'in_channels': 10, 'out_channels': 3, 'kernel_size': (11, 12), 'padding': 5, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 28, 'in_w': 25}


 59%|████████████████████████▊                 | 59/100 [00:50<00:24,  1.66it/s]

Result: True


Test: 59
Params: {'in_channels': 4, 'out_channels': 2, 'kernel_size': (12, 9), 'padding': 10, 'stride': 5, 'dilation': 3, 'groups': 2, 'in_batches': 3, 'in_h': 18, 'in_w': 18}
Result: False


Test: 60
Params: {'in_channels': 5, 'out_channels': 5, 'kernel_size': (3, 2), 'padding': 8, 'stride': 5, 'dilation': 5, 'groups': 1, 'in_batches': 3, 'in_h': 11, 'in_w': 25}


 62%|██████████████████████████                | 62/100 [00:51<00:16,  2.33it/s]

Result: True


Test: 61
Params: {'in_channels': 5, 'out_channels': 2, 'kernel_size': (11, 2), 'padding': 6, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 2, 'in_h': 16, 'in_w': 13}
Result: True


Test: 62
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (3, 7), 'padding': 3, 'stride': 2, 'dilation': 5, 'groups': 1, 'in_batches': 5, 'in_h': 32, 'in_w': 33}


 64%|██████████████████████████▉               | 64/100 [00:51<00:12,  2.87it/s]

Result: True


Test: 63
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (10, 9), 'padding': 7, 'stride': 4, 'dilation': 3, 'groups': 1, 'in_batches': 5, 'in_h': 16, 'in_w': 29}
Result: True


Test: 64
Params: {'in_channels': 2, 'out_channels': 1, 'kernel_size': (16, 3), 'padding': 4, 'stride': 2, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 30, 'in_w': 18}


 65%|███████████████████████████▎              | 65/100 [00:52<00:10,  3.37it/s]

Result: True


Test: 65
Params: {'in_channels': 7, 'out_channels': 4, 'kernel_size': (1, 5), 'padding': 5, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 21, 'in_w': 12}


 66%|███████████████████████████▋              | 66/100 [00:52<00:10,  3.18it/s]

Result: True


Test: 66
Params: {'in_channels': 11, 'out_channels': 5, 'kernel_size': (4, 7), 'padding': 9, 'stride': 4, 'dilation': 1, 'groups': 1, 'in_batches': 5, 'in_h': 5, 'in_w': 8}


 67%|████████████████████████████▏             | 67/100 [00:53<00:14,  2.28it/s]

Result: True


Test: 67
Params: {'in_channels': 9, 'out_channels': 7, 'kernel_size': (9, 7), 'padding': 8, 'stride': 1, 'dilation': 4, 'groups': 1, 'in_batches': 2, 'in_h': 19, 'in_w': 21}


 69%|████████████████████████████▉             | 69/100 [01:04<01:16,  2.45s/it]

Result: True


Test: 68
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (18, 9), 'padding': 4, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 2, 'in_h': 22, 'in_w': 13}
Result: True


Test: 69
Params: {'in_channels': 3, 'out_channels': 1, 'kernel_size': (3, 13), 'padding': 9, 'stride': 5, 'dilation': 3, 'groups': 1, 'in_batches': 3, 'in_h': 23, 'in_w': 20}
Result: True


Test: 70
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (17, 17), 'padding': 7, 'stride': 4, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 20, 'in_w': 30}


 71%|█████████████████████████████▊            | 71/100 [01:04<00:40,  1.41s/it]

Result: True


Test: 71
Params: {'in_channels': 3, 'out_channels': 1, 'kernel_size': (12, 13), 'padding': 10, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 2, 'in_h': 9, 'in_w': 33}


 72%|██████████████████████████████▏           | 72/100 [01:05<00:32,  1.15s/it]

Result: True


Test: 72
Params: {'in_channels': 12, 'out_channels': 12, 'kernel_size': (2, 1), 'padding': 2, 'stride': 1, 'dilation': 7, 'groups': 2, 'in_batches': 5, 'in_h': 18, 'in_w': 26}


 75%|███████████████████████████████▌          | 75/100 [01:11<00:37,  1.49s/it]

Result: False


Test: 73
Params: {'in_channels': 8, 'out_channels': 4, 'kernel_size': (18, 8), 'padding': 6, 'stride': 5, 'dilation': 1, 'groups': 4, 'in_batches': 2, 'in_h': 9, 'in_w': 14}
Result: False


Test: 74
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (11, 18), 'padding': 9, 'stride': 5, 'dilation': 1, 'groups': 2, 'in_batches': 4, 'in_h': 27, 'in_w': 8}
Result: True


Test: 75
Params: {'in_channels': 5, 'out_channels': 4, 'kernel_size': (4, 11), 'padding': 9, 'stride': 5, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 17, 'in_w': 29}


 76%|███████████████████████████████▉          | 76/100 [01:11<00:28,  1.20s/it]

Result: True


Test: 76
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (6, 20), 'padding': 9, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 22, 'in_w': 29}


 77%|████████████████████████████████▎         | 77/100 [01:12<00:22,  1.02it/s]

Result: True


Test: 77
Params: {'in_channels': 4, 'out_channels': 1, 'kernel_size': (1, 7), 'padding': 4, 'stride': 2, 'dilation': 5, 'groups': 1, 'in_batches': 2, 'in_h': 32, 'in_w': 32}
Result: True


Test: 78
Params: {'in_channels': 4, 'out_channels': 1, 'kernel_size': (20, 2), 'padding': 2, 'stride': 1, 'dilation': 1, 'groups': 1, 'in_batches': 2, 'in_h': 34, 'in_w': 16}


 79%|█████████████████████████████████▏        | 79/100 [01:12<00:13,  1.54it/s]

Result: True


Test: 79
Params: {'in_channels': 15, 'out_channels': 15, 'kernel_size': (10, 13), 'padding': 10, 'stride': 5, 'dilation': 3, 'groups': 3, 'in_batches': 1, 'in_h': 15, 'in_w': 29}


 80%|█████████████████████████████████▌        | 80/100 [01:14<00:16,  1.19it/s]

Result: False


Test: 80
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (9, 7), 'padding': 10, 'stride': 3, 'dilation': 5, 'groups': 1, 'in_batches': 4, 'in_h': 34, 'in_w': 27}


 81%|██████████████████████████████████        | 81/100 [01:14<00:14,  1.35it/s]

Result: True


Test: 81
Params: {'in_channels': 15, 'out_channels': 14, 'kernel_size': (5, 2), 'padding': 5, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 3, 'in_h': 34, 'in_w': 17}


 82%|██████████████████████████████████▍       | 82/100 [01:16<00:21,  1.18s/it]

Result: True


Test: 82
Params: {'in_channels': 2, 'out_channels': 2, 'kernel_size': (19, 8), 'padding': 6, 'stride': 1, 'dilation': 1, 'groups': 1, 'in_batches': 3, 'in_h': 18, 'in_w': 6}


 83%|██████████████████████████████████▊       | 83/100 [01:17<00:17,  1.03s/it]

Result: True


Test: 83
Params: {'in_channels': 3, 'out_channels': 3, 'kernel_size': (10, 7), 'padding': 10, 'stride': 1, 'dilation': 3, 'groups': 3, 'in_batches': 4, 'in_h': 33, 'in_w': 17}


 84%|███████████████████████████████████▎      | 84/100 [01:26<00:51,  3.21s/it]

Result: True


Test: 84
Params: {'in_channels': 6, 'out_channels': 6, 'kernel_size': (6, 4), 'padding': 9, 'stride': 4, 'dilation': 2, 'groups': 3, 'in_batches': 5, 'in_h': 15, 'in_w': 13}


 85%|███████████████████████████████████▋      | 85/100 [01:27<00:37,  2.48s/it]

Result: False


Test: 85
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (17, 9), 'padding': 6, 'stride': 4, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 10, 'in_w': 33}
Result: True


Test: 86
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (7, 4), 'padding': 10, 'stride': 2, 'dilation': 6, 'groups': 1, 'in_batches': 2, 'in_h': 17, 'in_w': 14}
Result: True


Test: 87
Params: {'in_channels': 18, 'out_channels': 18, 'kernel_size': (13, 12), 'padding': 1, 'stride': 4, 'dilation': 1, 'groups': 9, 'in_batches': 4, 'in_h': 31, 'in_w': 13}


 88%|████████████████████████████████████▉     | 88/100 [01:27<00:14,  1.21s/it]

Result: False


Test: 88
Params: {'in_channels': 8, 'out_channels': 2, 'kernel_size': (10, 20), 'padding': 7, 'stride': 3, 'dilation': 1, 'groups': 2, 'in_batches': 4, 'in_h': 22, 'in_w': 23}


 89%|█████████████████████████████████████▍    | 89/100 [01:28<00:12,  1.16s/it]

Result: False


Test: 89
Params: {'in_channels': 8, 'out_channels': 2, 'kernel_size': (4, 2), 'padding': 7, 'stride': 2, 'dilation': 3, 'groups': 2, 'in_batches': 4, 'in_h': 21, 'in_w': 24}


 90%|█████████████████████████████████████▊    | 90/100 [01:29<00:10,  1.09s/it]

Result: False


Test: 90
Params: {'in_channels': 4, 'out_channels': 3, 'kernel_size': (1, 8), 'padding': 5, 'stride': 2, 'dilation': 5, 'groups': 1, 'in_batches': 1, 'in_h': 18, 'in_w': 34}
invalid input parameters: output width is negative
Result: False


Test: 91
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (16, 19), 'padding': 1, 'stride': 2, 'dilation': 1, 'groups': 1, 'in_batches': 1, 'in_h': 17, 'in_w': 32}
Result: True


Test: 92
Params: {'in_channels': 6, 'out_channels': 3, 'kernel_size': (1, 11), 'padding': 9, 'stride': 1, 'dilation': 3, 'groups': 1, 'in_batches': 2, 'in_h': 7, 'in_w': 32}
invalid input parameters: output width is negative
Result: True


Test: 93
Params: {'in_channels': 18, 'out_channels': 15, 'kernel_size': (10, 7), 'padding': 1, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 5, 'in_h': 22, 'in_w': 10}


 95%|███████████████████████████████████████▉  | 95/100 [01:31<00:03,  1.46it/s]

Result: True


Test: 94
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (9, 16), 'padding': 5, 'stride': 1, 'dilation': 1, 'groups': 1, 'in_batches': 3, 'in_h': 8, 'in_w': 16}
Result: True


Test: 95
Params: {'in_channels': 5, 'out_channels': 3, 'kernel_size': (5, 6), 'padding': 8, 'stride': 4, 'dilation': 2, 'groups': 1, 'in_batches': 4, 'in_h': 34, 'in_w': 22}


 96%|████████████████████████████████████████▎ | 96/100 [01:33<00:03,  1.25it/s]

Result: True


Test: 96
Params: {'in_channels': 1, 'out_channels': 1, 'kernel_size': (15, 6), 'padding': 2, 'stride': 4, 'dilation': 2, 'groups': 1, 'in_batches': 3, 'in_h': 26, 'in_w': 10}
Result: True


Test: 97
Params: {'in_channels': 15, 'out_channels': 12, 'kernel_size': (1, 12), 'padding': 7, 'stride': 5, 'dilation': 2, 'groups': 3, 'in_batches': 5, 'in_h': 19, 'in_w': 19}


 99%|█████████████████████████████████████████▌| 99/100 [01:33<00:00,  2.00it/s]

Result: False


Test: 98
Params: {'in_channels': 6, 'out_channels': 4, 'kernel_size': (1, 1), 'padding': 10, 'stride': 2, 'dilation': 9, 'groups': 1, 'in_batches': 4, 'in_h': 26, 'in_w': 22}
Result: True


Test: 99
Params: {'in_channels': 12, 'out_channels': 1, 'kernel_size': (13, 8), 'padding': 7, 'stride': 3, 'dilation': 1, 'groups': 1, 'in_batches': 4, 'in_h': 32, 'in_w': 29}


100%|█████████████████████████████████████████| 100/100 [01:35<00:00,  1.05it/s]

Result: True


86 out of 100 (86.0%) tests passed


### Modular code for methods in `forward()`

### Modular code for `forward()`

### Old `Conv2D` code  for reference