### `Sigmoid` code

In [24]:
import numpy as np
import torch # needed for tests
from tqdm import tqdm # needed for tests

In [25]:
class Sigmoid:
    ''' Computes Sigmoid activation given the input '''
    
    ''' * The class implementation will be along the lines of torch.nn.Sigmoid in order to 
          enable comparison of this NumPy only implementation and seamless testing
        * Can expect extensive refactoring of the existing code in the days to come
        * As part of refactoring, some code will be de-modularized
        * Old code will be retained at the end of the notebook for reference
    '''
    '''
        TODO:
        * Replace `torch.round()` with `np.allclose()` for tests
        * Optimizing code
    '''
    
    def __init__(
        self,
        inplace = False,
        verbose = False
        ):
        super(Sigmoid, self).__init__()
        
        ''' mandatory parameters '''
        # None
        
        ''' optional parameters '''
        # None
        
        ''' optional parameters (dummy, yet to be implemented)'''
        # None
        
        ''' additional parameters (different from torch.nn.Conv2D)'''
        self.verbose = verbose
        self.verboseprint = print if self.verbose else lambda *a, **k: None
        self.verboseprint('*** parameters ***')
        self.verboseprint('\n')
    
    def forward(self, _input):
        ''' forward pass to perform Sigmoid activation '''
        
        ''' error checking '''
        if not (isinstance(_input, int) or isinstance(_input, float) or isinstance(_input, np.ndarray)):
            raise Exception('invalid input: input should either be an int, a float, or a NumPy ndarray')
            
        ''' compute Sigmoid activation '''
        output = 1 / (1 + np.exp(-_input))
        self.verboseprint(output)
        self.verboseprint('\n')
        return output

### Standalone test (random input)

In [26]:
_input = np.random.rand(10, 20, 3) # define a random input

In [27]:
# get Sigmoid output with the random input

sigmoid = Sigmoid(_input) # call an instance of the class with the input
_output = sigmoid.forward(_input) # perform Sigmoid activation
print("*** Sigmoid output ***")
print(_output)

*** Sigmoid output ***
[[[0.60853075 0.70793628 0.5035494 ]
  [0.59485843 0.58181536 0.72567081]
  [0.6531097  0.5710276  0.52397209]
  [0.58895698 0.67440179 0.63225884]
  [0.55842298 0.6522823  0.52263639]
  [0.56676411 0.54063506 0.6691447 ]
  [0.61309273 0.54396323 0.62509763]
  [0.61500979 0.58643033 0.55167669]
  [0.61788871 0.70428184 0.67189323]
  [0.72122775 0.65556317 0.64341647]
  [0.52028587 0.57527901 0.71376106]
  [0.57870541 0.72334992 0.7017357 ]
  [0.66552929 0.61539584 0.69850748]
  [0.68352541 0.50177195 0.52860042]
  [0.59715015 0.61631093 0.72337192]
  [0.65830494 0.61197586 0.5193315 ]
  [0.50809015 0.62800767 0.67940947]
  [0.6802552  0.62494572 0.68995084]
  [0.66850854 0.51196524 0.64252593]
  [0.67863459 0.60469969 0.5873672 ]]

 [[0.52898516 0.67639648 0.70896409]
  [0.58675285 0.64686905 0.68477504]
  [0.53505905 0.5831935  0.69788618]
  [0.72192877 0.55231765 0.53938478]
  [0.71552182 0.66467074 0.56262522]
  [0.55333452 0.69784257 0.69832929]
  [0.62979838

In [28]:
# get PyTorch output with the same random inputs as above

x = torch.DoubleTensor(_input)
m = torch.nn.Sigmoid()
output = m(x)
print("*** PyTorch output ***")
print(output)

*** PyTorch output ***
tensor([[[0.6085, 0.7079, 0.5035],
         [0.5949, 0.5818, 0.7257],
         [0.6531, 0.5710, 0.5240],
         [0.5890, 0.6744, 0.6323],
         [0.5584, 0.6523, 0.5226],
         [0.5668, 0.5406, 0.6691],
         [0.6131, 0.5440, 0.6251],
         [0.6150, 0.5864, 0.5517],
         [0.6179, 0.7043, 0.6719],
         [0.7212, 0.6556, 0.6434],
         [0.5203, 0.5753, 0.7138],
         [0.5787, 0.7233, 0.7017],
         [0.6655, 0.6154, 0.6985],
         [0.6835, 0.5018, 0.5286],
         [0.5972, 0.6163, 0.7234],
         [0.6583, 0.6120, 0.5193],
         [0.5081, 0.6280, 0.6794],
         [0.6803, 0.6249, 0.6900],
         [0.6685, 0.5120, 0.6425],
         [0.6786, 0.6047, 0.5874]],

        [[0.5290, 0.6764, 0.7090],
         [0.5868, 0.6469, 0.6848],
         [0.5351, 0.5832, 0.6979],
         [0.7219, 0.5523, 0.5394],
         [0.7155, 0.6647, 0.5626],
         [0.5533, 0.6978, 0.6983],
         [0.6298, 0.5287, 0.6663],
         [0.6429, 0.5941, 0.68

In [29]:
# compare outputs of Conv2D and PyTorch
print(torch.equal(torch.round(torch.DoubleTensor(_output)), torch.round(output))) # need to round the output due to precision difference

True


### Extensive tests (random input)

In [30]:
def run_tests(num_tests):
    ''' sweep different input parameters and test by comparing outputs of Sigmoid and PyTorch '''
    
    num_passed = 0
    print('Number of tests: {}\n\n'.format(num_tests))
    
    for i in tqdm(range(num_tests)):
        num_dim = np.random.randint(6) + 1 # number of input dimensions
        dim = tuple(np.random.randint(5) + 1 for _ in range(num_dim)) # shape of input
        _input = np.random.rand(*dim) # generate an input based on the dimensions and shape
        print('Test: {}\nInput shape: {}'.format(i, dim))
        
        try:
            # get Sigmoid output with the random input
            sigmoid = Sigmoid(_input) # call an instance of the class with the input
            _output = sigmoid.forward(_input) # perform Sigmoid activation

            # get PyTorch output with the same random input as above
            x = torch.DoubleTensor(_input)
            m = torch.nn.Sigmoid()
            output = m(x)
            
        except Exception as e:
            print(e)
            print('Result: False\n\n') # treating exception as a failed test
            continue

        # compare outputs of Sigmoid and PyTorch
        result = torch.equal(torch.round(torch.DoubleTensor(_output)), torch.round(output)) # need to round the output due to precision difference
        print('Result: {}\n\n'.format(result))
        if result:
            num_passed += 1

    print('{} out of {} ({}%) tests passed'.format(num_passed, num_tests, float(100 * num_passed / num_tests)))


In [31]:
num_tests = 1000
run_tests(num_tests)

Number of tests: 1000




 31%|███████████▋                          | 308/1000 [00:00<00:00, 3079.84it/s]

Test: 0
Input shape: (1,)
Result: True


Test: 1
Input shape: (5, 2)
Result: True


Test: 2
Input shape: (1, 1)
Result: True


Test: 3
Input shape: (1,)
Result: True


Test: 4
Input shape: (3, 5, 5)
Result: True


Test: 5
Input shape: (1, 4, 1, 5)
Result: True


Test: 6
Input shape: (5, 4, 1, 4, 4, 1)
Result: True


Test: 7
Input shape: (3, 5, 4, 5, 4)
Result: True


Test: 8
Input shape: (4, 4, 1, 5, 1)
Result: True


Test: 9
Input shape: (3, 5, 2, 5)
Result: True


Test: 10
Input shape: (1, 5)
Result: True


Test: 11
Input shape: (3, 4, 4, 3, 5, 2)
Result: True


Test: 12
Input shape: (1, 1, 3, 4, 5, 3)
Result: True


Test: 13
Input shape: (5, 1, 3, 2)
Result: True


Test: 14
Input shape: (4,)
Result: True


Test: 15
Input shape: (2, 2, 2, 3, 4)
Result: True


Test: 16
Input shape: (1, 3)
Result: True


Test: 17
Input shape: (4, 1)
Result: True


Test: 18
Input shape: (4, 4)
Result: True


Test: 19
Input shape: (4, 4, 5, 2)
Result: True


Test: 20
Input shape: (2, 1, 1)
Result: True



 96%|████████████████████████████████████▌ | 962/1000 [00:00<00:00, 5114.94it/s]

Result: True


Test: 909
Input shape: (3,)
Result: True


Test: 910
Input shape: (3, 2, 3, 2)
Result: True


Test: 911
Input shape: (3, 1)
Result: True


Test: 912
Input shape: (4, 2, 1, 3)
Result: True


Test: 913
Input shape: (3, 5, 3, 1, 4)
Result: True


Test: 914
Input shape: (5,)
Result: True


Test: 915
Input shape: (2, 2, 1, 4, 5)
Result: True


Test: 916
Input shape: (4, 1)
Result: True


Test: 917
Input shape: (1, 4)
Result: True


Test: 918
Input shape: (3, 1)
Result: True


Test: 919
Input shape: (1, 2, 5, 3, 1, 4)
Result: True


Test: 920
Input shape: (4,)
Result: True


Test: 921
Input shape: (4, 3, 3)
Result: True


Test: 922
Input shape: (3, 1, 3, 1, 2, 5)
Result: True


Test: 923
Input shape: (4, 1, 5)
Result: True


Test: 924
Input shape: (2, 3)
Result: True


Test: 925
Input shape: (5, 1, 1, 5)
Result: True


Test: 926
Input shape: (3, 3)
Result: True


Test: 927
Input shape: (2,)
Result: True


Test: 928
Input shape: (2, 4, 2, 1, 5, 3)
Result: True


Test: 929
Input

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 4575.84it/s]

Test: 969
Input shape: (4, 4, 3, 5, 5)
Result: True


Test: 970
Input shape: (5, 3, 3, 1, 5, 1)
Result: True


Test: 971
Input shape: (5,)
Result: True


Test: 972
Input shape: (5, 2, 5, 5, 3, 4)
Result: True


Test: 973
Input shape: (2, 1, 2)
Result: True


Test: 974
Input shape: (1,)
Result: True


Test: 975
Input shape: (3, 5, 3, 3)
Result: True


Test: 976
Input shape: (3, 5, 4)
Result: True


Test: 977
Input shape: (3, 2, 5, 3, 5, 4)
Result: True


Test: 978
Input shape: (1, 2, 1, 3, 4)
Result: True


Test: 979
Input shape: (1, 3, 2, 5)
Result: True


Test: 980
Input shape: (5, 2, 1)
Result: True


Test: 981
Input shape: (1,)
Result: True


Test: 982
Input shape: (5,)
Result: True


Test: 983
Input shape: (1,)
Result: True


Test: 984
Input shape: (2, 3, 3)
Result: True


Test: 985
Input shape: (3, 5, 5, 3, 2, 4)
Result: True


Test: 986
Input shape: (1,)
Result: True


Test: 987
Input shape: (3, 5, 5, 5)
Result: True


Test: 988
Input shape: (2,)
Result: True


Test: 989
Input sh